version: '3.8'

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: uptc2024
      POSTGRES_DB: AccessControlCommandDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: uptc2024
      MONGO_INITDB_DATABASE: AccessControlQueryDB
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: