version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true                   # Habilita el dashboard (solo para desarrollo)
      - --providers.docker=true               # Habilita el provider de Docker
      - --providers.docker.exposedbydefault=false # Solo exponer servicios explícitamente
      - --entrypoints.web.address=:80         # Puerto de entrada HTTP
      - --entrypoints.web.http.middlewares=cors-headers
      - --providers.file.filename=/etc/traefik/dynamic.yml
    ports:
      - "80:80"                               # Puerto para el tráfico HTTP
      - "8070:8080"                           # Puerto del dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Para descubrir servicios Docker
      - ./dynamic.yml:/etc/traefik/dynamic.yml     # Configuración dinámica
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge